name: alphatracker
channels:
  - https://repo.anaconda.com/pkgs/free
  - https://conda.binstar.org/cyclus
  - https://conda.binstar.org/vgauthier
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1=main
  - attrs=19.1.0=py36_1
  - backcall=0.1.0=py36_0
  - blas=1.0=mkl
  - bleach=3.1.0=py36_0
  - ca-certificates=2019.10.16=0
  - certifi=2019.9.11=py36_0
  - cloudpickle=1.2.2=py_0
  - cython
  - cytoolz=0.10.1=py36h7b6447c_0
  - dask-core=2.8.0=py_0
  - dbus=1.13.6=h746ee38_0
  - decorator=4.4.0=py36_1
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py36_0
  - expat=2.2.6=he6710b0_0
  - fontconfig=2.13.0=h9420a91_0
  - freetype=2.9.1=h8a8886c_1
  - glib=2.56.2=hd408876_0
  - gmp=6.1.2=h6c8ec71_1
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb453b48_1
  - icu=58.2=h9c2bf20_1
  - imageio=2.6.1=py36_0
  - intel-openmp=2019.4=243
  - ipykernel=5.1.0=py36h39e3cac_0
  - ipython=7.5.0=py36h39e3cac_0
  - ipython_genutils=0.2.0=py36_0
  - ipywidgets=7.4.2=py36_0
  - jedi=0.13.3=py36_0
  - jinja2=2.10.1=py36_0
  - joblib=0.13.2=py36_0
  - jpeg=9b=h024ee3a_2
  - jsonschema=3.0.1=py36_0
  - jupyter=1.0.0=py36_7
  - jupyter_client=5.2.4=py36_0
  - jupyter_console=6.0.0=py36_0
  - jupyter_core=4.4.0=py36_0
  - libedit=3.1=heed3624_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=8.2.0=hdf63c60_1
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libsodium=1.0.16=h1bed415_0
  - libstdcxx-ng=8.2.0=hdf63c60_1
  - libtiff=4.0.10=h2733197_2
  - libuuid=1.0.3=h1bed415_2
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.9=he19cac6_0
  - libxslt=1.1.33=h7d1a2b0_0
  - lxml=4.4.1=py36hefd8a0e_0
  - markupsafe=1.1.1=py36h7b6447c_0
  - mistune=0.8.4=py36h7b6447c_0
  - mkl=2018.0.3=1
  - munkres=1.0.12=py_0
  - nbconvert=5.5.0=py_0
  - nbformat=4.4.0=py36_0
  - ncurses=6.0=h9df7e31_2
  - networkx=2.4=py_0
  - notebook=5.7.8=py36_0
  - olefile=0.46=py36_0
  - openssl=1.0.2t=h7b6447c_1
  - pandoc=2.2.3.2=0
  - pandocfilters=1.4.2=py36_1
  - parso=0.4.0=py_0
  - patsy=0.5.1=py36_0
  - pcre=8.43=he6710b0_0
  - pexpect=4.7.0=py36_0
  - pickleshare=0.7.5=py36_0
  - pip=19.0.3=py36_0
  - prometheus_client=0.6.0=py36_0
  - prompt_toolkit=2.0.9=py36_0
  - ptyprocess=0.6.0=py36_0
  - pygments=2.4.0=py_0
  - pyqt=5.9.2=py36h05f1152_2
  - pyrsistent=0.14.11=py36h7b6447c_0
  - python=3.6.2=hca45abc_19
  - python-dateutil=2.8.0=py36_0
  - pywavelets=1.0.3=py36hdd07704_1
  - pyzmq=18.0.0=py36he6710b0_0
  - qt=5.9.6=h52aff34_0
  - qtconsole=4.4.4=py_0
  - readline=7.0=ha6073c6_4
  - scikit-image=0.15.0=py36he6710b0_0
  - scikit-learn=0.20.1=py36h4989274_0
  - seaborn=0.9.0=py36_0
  - send2trash=1.5.0=py36_0
  - setuptools=40.8.0=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.12.0=py36_0
  - sqlite=3.23.1=he433501_0
  - statsmodels=0.10.1=py36hdd07704_0
  - terminado=0.8.2=py36_0
  - testpath=0.4.2=py36_0
  - tk=8.6.8=hbc83047_0
  - toolz=0.10.0=py_0
  - tornado=6.0.2=py36h7b6447c_0
  - traitlets=4.3.2=py36h674d592_0
  - wcwidth=0.1.7=py36_0
  - webencodings=0.5.1=py36_1
  - wheel=0.33.1=py36_0
  - widgetsnbextension=3.4.2=py36_0
  - xz=5.2.4=h14c3975_4
  - zeromq=4.3.1=he6710b0_3
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.3.7=h0b5b093_0
  - pytz=2018.9
  - pip:
    - bz2file==0.98
    - chardet==3.0.4
    - cycler==0.10.0
    - filterpy==1.4.5
    - "git+https://github.com/ZexinChen/torchsample"
    - h5py==2.9.0
    - idna==2.8
    - kiwisolver==1.0.1
    - llvmlite==0.33.0
    - matplotlib==3.0.3
    - nibabel==2.3.3
    - numba==0.50.1
    - numpy==1.17.0
    - opencv-python==4.0.0.21
    - pandas==0.24.2
    - pillow==5.4.1
    - protobuf==3.7.1
    - pycocotools==2.0.0
    - pyparsing==2.3.1
    - requests==2.21.0
    - scipy==1.3.1
    - tensorboardx==1.6
    - torch==0.4.0
    - torchfile==0.1.0
    - torchvision==0.2.2.post3
    - tqdm==4.31.1
    - umap-learn==0.4.6
    - urllib3==1.24.1
    - visdom==0.1.8.8
    - websocket-client==0.56.0
    - pca
    - googledrivedownloader
prefix: /home/zexin/.conda/envs/alphatracker

